title: LABS - Sound and Vision
timezone: Europe/Amsterdam
collections:
  apis:
    title: APIs
    output: true
    permalink: "/api/:title"
  applications:
    title: Applications
    output: true
    permalink: "/application/:title"
  datasets:
    title: Datasets
    output: true
    permalink: "/dataset/:title"
  examples:
    title: Examples
    output: true
    permalink: "/example/:title"
  projects:
    title: Projects
    output: true
    permalink: "/project/:title"
  uploads:
    title: Uploads
    output: true

email: rd@beeldengeluid.nl
description: >- # this means to ignore newlines until "baseurl:"
  showcases tools, demos and prototypes developed by the R&D department of the Netherlands Institute for Sound and Vision
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: benglabs
github_username:  beeldengeluid

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
